# Generated by Django 4.2.13 on 2024-11-21 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('header', '0002_alter_header_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='header',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='header',
            name='user',
        ),
        migrations.AddField(
            model_name='header',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='github',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='header',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='header',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='header',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
