# Generated by Django 4.2.13 on 2024-11-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperience', '0002_alter_workexperience_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='accomplishments',
            field=models.JSONField(),
        ),
    ]
