# Generated by Django 4.2.13 on 2024-11-21 04:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperience', '0003_alter_workexperience_accomplishments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='accomplishments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
