# Generated by Django 4.2.13 on 2024-11-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workexperience', '0004_alter_workexperience_accomplishments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='description',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='role',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='accomplishments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
